language: erlang
sudo: required
dist: trusty
before_install:
 - psql --version
 - sudo service postgresql stop
 - export DEBIAN_FRONTEND=noninteractive;
 - sudo -E apt-get -yq update &>> ~/apt-get-update.log;
 - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.5-postgis-2.2
script:
- psql --version
