os:
  - osx
  - linux
language: python
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3
compiler:
  - clang
script:
 - clang --version
