sudo: required
language:	android
jdk:	oraclejdk8
android:
 components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-23
  - sys-img-armeabi-v7a-android-23
