language: objective-c
cache:
directories:
- node_modules
- /usr/local/lib/node_modules/
- /home/travis/android-sdk-linux/
- /home/travis/.nvm/
os: osx
osx_image: xcode7
before_install:
- export LANG=en_US.UTF-8
- npm install -g npm@2.14.5
- npm install -g cordova ionic
- brew install android-sdk
- android update sdk --no-ui -a --filter 142
